# Generated by Django 2.2.5 on 2019-10-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('fathers_name', models.CharField(max_length=64)),
                ('AIR', models.IntegerField()),
                ('course', models.CharField(max_length=64)),
            ],
        ),
    ]
